---
abstract: 'Require a successful GitHub Actions workflow run'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test2::V0: '0'
  Test::DiagINC: '0.002'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-GitHub-RequireGreenBuild
no_index:
  directory:
    - t
    - xt
requires:
  Dist::Zilla::Plugin::Bootstrap::lib: '0'
  Dist::Zilla::Plugin::GitHub: '0'
  Dist::Zilla::Plugin::MetaJSON: '0'
  Dist::Zilla::Plugin::MetaYAML: '0'
  Dist::Zilla::Plugin::RunExtraTests: '0'
  Dist::Zilla::Plugin::Test::EOF: '0'
  Dist::Zilla::Plugin::Test::EOL: '0'
resources:
  repository: git://github.com/bleargh45/playground.git
version: '0.01'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Artistic-2.0
x_static_install: 1
