---
abstract: 'Require a successful GitHub Actions workflow run'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::DiagINC: '0.002'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-GitHub-RequireGreenBuild
no_index:
  directory:
    - t
    - xt
requires:
  Dist::Zilla: '0'
  Dist::Zilla::Plugin::GitHub: '0'
  Git::Wrapper: '0'
  HTTP::Tiny: '0'
  Moose: '0'
  namespace::clean: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/bleargh45/Dist-Zilla-Plugin-GitHub-RequireGreenBuild/issues
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-GitHub-RequireGreenBuild/
  repository: git://github.com/bleargh45/Dist-Zilla-Plugin-GitHub-RequireGreenBuild.git
version: '0.04'
x_generated_by_perl: v5.36.1
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: Artistic-2.0
x_static_install: 1
